@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Estudiante {
  + Estudiante(Long, String, String): 
  - id: Long
  - apellido: String
  - nombre: String
  + toString(): String
   apellido: String
   id: Long
   nombre: String
}
class EstudianteDaoEnMemoria {
  + EstudianteDaoEnMemoria(List<Estudiante>): 
  + buscar(Long): Estudiante
  + eliminar(Long): void
  + guardar(Estudiante): Estudiante
  + buscarTodos(): List<Estudiante>
}
class EstudianteDaoEnMemoriaTest {
  + EstudianteDaoEnMemoriaTest(): 
  + guardarYBuscarEstudiantesTest(): void
  + traerTodosLosEstudiantesTest(): void
  + eliminarEstudianteTest(): void
  + cargarEstudiantes(): void
}
class EstudianteDaoH2 {
  + EstudianteDaoH2(): 
  + eliminar(Long): void
  + buscarTodos(): List<Estudiante>
  + guardar(Estudiante): Estudiante
  + buscar(Long): Estudiante
}
class EstudianteDaoH2Test {
  + EstudianteDaoH2Test(): 
  + cargarEstudiantes(): void
  + eliminarEstudiantesTest(): void
  + guardarYBuscarEstudiantesTest(): void
  + traerTodosLosEstudiantesTest(): void
}
class EstudianteService {
  + EstudianteService(IDao<Estudiante>): 
  + EstudianteService(): 
  - estudianteDao: IDao<Estudiante>
  + buscar(Long): Estudiante
  + eliminarEstudiante(Long): void
  + guardarEstudiante(Estudiante): Estudiante
  + buscarTodos(): List<Estudiante>
   estudianteDao: IDao<Estudiante>
}
class EstudianteServiceTest {
  + EstudianteServiceTest(): 
  + buscarEstudiantesCambiandoImplementacionDAO(): void
  + cargarEstudiantesCambiandoImplementacionDAO(): void
}
interface IDao<T> << interface >> {
  + eliminar(Long): void
  + buscar(Long): T
  + guardar(T): T
  + buscarTodos(): List<T>
}
class Main {
  + Main(): 
  + main(String[]): void
}

EstudianteDaoEnMemoria     "1" *-[#595959,plain]-> "estudianteRepositorio\n*" Estudiante                 
EstudianteDaoEnMemoria      -[#008200,dashed]-^  IDao                       
EstudianteDaoEnMemoriaTest  -[#595959,dashed]->  Estudiante                 : "«create»"
EstudianteDaoEnMemoriaTest  -[#595959,dashed]->  EstudianteDaoEnMemoria     : "«create»"
EstudianteDaoEnMemoriaTest "1" *-[#595959,plain]-> "estudianteDao\n1" IDao                       
EstudianteDaoH2             -[#595959,dashed]->  Estudiante                 : "«create»"
EstudianteDaoH2             -[#008200,dashed]-^  IDao                       
EstudianteDaoH2Test         -[#595959,dashed]->  Estudiante                 : "«create»"
EstudianteDaoH2Test         -[#595959,dashed]->  EstudianteDaoH2            : "«create»"
EstudianteDaoH2Test        "1" *-[#595959,plain]-> "estudianteDao\n1" IDao                       
EstudianteService          "1" *-[#595959,plain]-> "estudianteDao\n1" IDao                       
EstudianteServiceTest       -[#595959,dashed]->  Estudiante                 : "«create»"
EstudianteServiceTest       -[#595959,dashed]->  EstudianteDaoEnMemoria     : "«create»"
EstudianteServiceTest       -[#595959,dashed]->  EstudianteDaoH2            : "«create»"
EstudianteServiceTest      "1" *-[#595959,plain]-> "estudianteService\n1" EstudianteService          
EstudianteServiceTest       -[#595959,dashed]->  EstudianteService          : "«create»"
EstudianteServiceTest      "1" *-[#595959,plain]-> "estudianteDaoEnMemoria\n1" IDao                       
@enduml
